### ISSUE TITLE
CSV Converter

### ISSUE THREAD

**Issue by devonpmack** [devonpmack/simulate_natural_selection#3]
Add download CSV button with just averages

**Comment by DavidHZhu** [comment]
remember in ICS4U when we were supposed to sort data from a CSV? and you know how the values are supposed to be COMMA SEPARATED but my csv had values like "austin,tx" but it was meant to be one value. Pepperidge farm remembers

**Comment by devonpmack** [comment]
@DavidHZhu that is your personal problem
